= Docker（続き）

== Dockerのネットワーク
* 起動しているコンテナについて、所属するネットワークを決定したり、別のネットワークに切り離したりできる。

== ネットワークの種類
ブリッジネットワーク :: 単一のDockerホスト内のコンテナ間で構成されるネットワーク。（小規模なネットワーク構成） +
デフォルトのブリッジネットワークでは、DNSのサービスが提供されていないため、通常名前解決ができない。
ノンネットワーク :: ループバックインタフェース以外にネットワークインタフェースを持たないネットワーク。 +
その他のすべてのネットワークを切断した状態。
ホストネットワーク :: Dockerホストと同じネットワーク。 +
ホストマシーンとコンテナのポート番号の統一化ができる。
オーバーレーネットワーク :: 複数のDockerマシン間で相互通信を可能にするためのネットワーク。 +
ホストの情報や状態管理を行うキーバリューストア（データベース）が外部に必要になる。
ユーザ定義のブリッジネットワーク :: 組み込みDNSが機能して名前解決等もしてくれる。 +
ブリッジネットワークを指定して接続したとき、デフォルトのブリッジネットワークは接続されない。

== Dockerのデータ管理
* 起動中のコンテナの読み書き可能なレイヤに置くこともできるが以下のデメリットがあるため、ホスト上のファイル、ディレクトリやメモリをコンテナにマウントする仕組みを利用するのが好ましい。

==== デメリット
* コンテナの削除で、データが消えてしまう。
* コンテナ間でのデータのやり取りができない。
* 書き込みのパフォーマンスが良くない。（unionファイルシステム利用のため）
    

.３種類のマウントタイプ
|=======================
|volume　|ホスト上のDockerエリアに自動的にディレクトリが作成される。 +
※このディレクトリを直接移動したり編集したりすることはない。
|bind mount　|ホストのユーザが管理しているファイルやディレクトリをコンテナにマウントする。
|tmpfs　|ホストのメモリ領域をファイルシステムとしてコンテナにマウントする。 +
※メモリ領域のため、コンテナやホストの停止等でデータが消える。
|=======================

==== volume、bind mountのメリット
* 複数のコンテナへのマウントが可能なため、コンテナ間で同じディレクトリの共有ができる。
* コンテナを削除してもホスト上にデータが残る。 +
※tmpfsは一時的に保存しておきたいデータの管理に適する。

==== コンテナ起動時のvolumeでのマウント　※同じホスト間でしか利用できない
. まだ存在しないvolume名を使用する
.. マウントポイントのディレクトリが空であるとき +
→ 空のvolumeが作成。
.. マウントポイントのディレクトリに既にファイルやディレクトリが存在するとき +
→ 作成されたvolumeに存在していたデータがコピーされる。
. 既に存在しているvolume名を使用するとき +
→ コンテナ上のファイルがvolumeにコピーされることはない。（既存のデータは隠れて見えない状態になる。）
. 読み取り専用のvolumeもマウントできる。

==== bind mountでのマウントの注意点
* マウントするとマウント先のファイルやディレクトリが隠れてしまう。 +
→ コンテナが正常に動作しない可能性が発生する。
* 読み取り専用のbind mountもできる。

== Docker composeとは
* マルチコンテナのDockerアプリケーションを定義して実行するためのツール。
* 複数のサーバをyamlファイルに記述することで、アプリケーションに必要なコンテナを同時に立ち上げることができる。
* 開発環境や自動テストの実行環境を立ち上げる際によく使用される。
