= Docker（前回の続き）

== ビルドコンテキストとは
* イメージを作成する際にアクセスできるディレクトリやファイルの範囲を示す。

==== 注意しなければならないこと
* ビルドすると一度まとめてDockerDeamonに送信されるため、ファイルサイズが大きいと転送処理に時間がかかってしまう。不要なファイルは削除しておくとよい。 +
※ただし、すべてのファイルがイメージに取り込まれるわけではない。

== ビルドのキャッシュ機能
* 一度実行したコマンドを保持する機能。
* 更新されていない内容についてはキャッシュ機能を用いて実行され、実際のコマンドは無視される。

==== 注意しなければならないこと
* 実行するコマンドは同じでも、実行した結果が毎回変わるコマンドには注意が必要。（パッケージのアップデート等）

==== キャッシュ機能の回避方法
* docker build コマンドのオプションに --no-cache を付ける。

== Docker Hub無料登録の注意点
* privateのリポジトリ登録は１つのみである。 +
※１つprivateのリポジトリを作ってしまっても、消せばまた作り直せる。 +
※後からpublicとprivateを切り替えることも可能。
* 自動ビルドのサービスは数年前に廃止している。（自動ビルドの内容については後述）

== レジストリサーバとは
* Dockerイメージをホスティングしているサーバ。（Docker Hub、Quay.io、独自のサーバ等）
ターミナルでのログインの必要性 :: docker login -u [user名]
Docker Hubのタグ付け :: <Docker ID>/<イメージ名>:(<タグ名>)

== コンテナの起動
* 実行したコマンドがフォアグラウンドで動作し続けている間はコンテナが起動中だが、処理が終了するとコンテナも自動的に停止する。
デタッチドモード -d :: コンテナをバックグラウンドで動作させる。

==== 注意しなければならないこと
* バックグラウンドの処理は待たずにコンテナが停止する。 +
※Dockerコンテナでは、フォアグラウンドで処理実行をするのが好ましい。

.コンテナのステータス
|=======================
|Running(Up)　|起動中
|Created　|作成したが、起動はしていない
|Pause　|一時停止中
|Exited　|起動後、停止
|Removing　|コンテナ削除中
|Dead　|正常に終了できずに残ってしまっている
|=======================
※コンテナの削除は瞬時に処理されるため、Removing を見ることはほとんどない。

== コンテナのシェルに接続する
docker attach コマンド :: コンテナで元々シェルを実行しているときに接続できる。 +
※シェルを実行していないとDeamonに接続されてしまうので、注意。
docker exec コマンド :: オプションに -it を付けると標準入出力でシェルに接続できる。

==== 注意しなければならないこと
* シェルを抜ける際に exit コマンドを実行すると attach コマンドはコンテナも停止してしまうため、誤ってコンテナを停止させることを防ぐためには exec コマンドを使用するのが好ましい。

== コンテナの状態をイメージとして保存する(docker commit コマンド)
* コンテナ内で作業したものをイメージとして保存すると作業過程は明確な記録として残らない。 +
※通常、Dockerfileからイメージをビルドした際には内容がわかりやすい。

== COPY命令とADD命令の違い
COPY命令 :: ファイルのコピーを行う。
ADD命令 :: COPYの機能+tarを自動で展開、URLからダウンロードしてコピー先に転送

※通常はCOPY命令で、必要な場合のみADD命令を行うのが好ましい。

== 参考
Automated Build（自動ビルド）とは :: Github等のソースコードのホスティングサービスで、ビルドコンテキストを管理し、リポジトリ上で内容変更があった際にDocker Hubへ自動的にビルドを実行する仕組み。
Docker Machineとは :: Docker Engineを搭載した仮想マシンの作成、起動、停止、再起動等をコマンドラインから実行できるツール。

