= LAMP環境構築手順書

== Dockerのインストール
. 古いバージョンのDockerをアンインストールする。
+
[source,yaml]
----
sudo apt-get remove docker docker-engine docker.io containerd runc
----

. Dockerエンジンのインストールをする。今回は、リポジトリのセットアップを利用する。
.. まずはaptパッケージの更新をする。
+
[source,yaml]
----
sudo apt-get update
----
.. 次に必要なパッケージのインストールをする。
+
[source,yaml]
----
sudo apt-get install ca-certificates curl gnupg lsb-release
----
.. Dockerの公式GPG鍵を追加する。
+
[source,yaml]
----
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
----
.. 安定版リポジトリのセットアップを行う。
+
[source,yaml]
----
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
----
.. さらに必要なパッケージのインストールをする。
+
[source,yaml]
----
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
----

. rootユーザ以外でDockerを管理するときの設定（参考）
.. dockerグループを作成する。
+
[source,yaml]
----
sudo groupadd docker
----
.. 一般ユーザをdockerグループに追加する。
+
[source,yaml]
----
sudo usermod -aG docker $USER
----
.. Linuxマシンを再起動する。
+
[source,yaml]
----
sudo shutdown -r now
----
.. dockerコマンドでhello-worldのイメージが実行できるか確認する。（参考）
+
[source,yaml]
----
docker run hello-world
----

== LAMP環境の確認
今回のLAMP環境の構成は以下のようにする。また、セキュリティのため、Apache、PHPとMySQLのDockerイメージを分けて作成する。 +
　　*L* : Linux（Ubuntu） +
　　*A* : Apache +
　　*M* : MySQL +
　　*P* : PHP +
簡単のため、作業するディレクトリを作成し、移動する。
[source,yaml]
----
mkdir lamp_server
cd lamp_server
----

== Dockerイメージの作成
. Apache、PHPのDockerイメージを作成する。
.. 作業するディレクトリを作成し、移動する。
+
[source,yaml]
----
mkdir web_build
cd web_build
----
.. Dockerfileを作成する。
+
[source,yaml]
----
vi Dockerfile
----
Dockerfileの中身 ::
+
[source,yaml]
----
# ubuntuをベースイメージとして使用する
FROM ubuntu:latest

# パッケージの更新、必要なパッケージのインストール
RUN apt update && apt -y install --no-install-recommends \
    apache2 \
    php \
    php-mysql \
 && rm -rf /var/lib/apt/lists/*

# index.htmlというファイルをドキュメントルートディレクトリに追加
ADD index.html /var/www/html/
# index.phpというファイルをドキュメントルートディレクトリに追加
ADD index.php /var/www/html/

# 必要なポート（httpの80番）を開く
EXPOSE 80

# コンテナ起動時にApacheをフォアグラウンドで起動する
CMD ["/usr/sbin/apache2ctl","-D","FOREGROUND"]
----
.. ApacheやPHPを動作させるときに必要なファイルを用意しておく。（ファイルの中身は任意）
+
[source,yaml]
----
vi index.html
vi index.php
----
.. イメージをビルドする。
+
[source,yaml]
----
docker build -t docker-web .
----
.. Dockerイメージが作成されたことを確認する。
+
[source,yaml]
----
docker images
----
作成したdocker-webという名前のイメージが表示されたらOK
.. Docker Hubにログインする。
+
[source,yaml]
----
Docker login -u [Docker ID]
----
パスワードを入力し、Login Succeededと表示されたらOK
.. イメージにタグ付けする。
+
[source,yaml]
----
docker tag docker-web [Docker ID]/docker-web:ver1
----
.. イメージをプッシュする。
+
[source,yaml]
----
docker push [Docker ID]/docker-web:ver1
----
Docker Hubのページを確認し、表示されていたらOK

. MySQLのDockerイメージを作成する。
.. 作業するディレクトリを作成し、移動する。
+
[source,yaml]
----
cd ..
mkdir mysql_build
cd mysql_build
----
.. Dockerfileを作成する。
+
[source,yaml]
----
vi Dockerfile
----
Dockerfileの中身 ::
+
[source,yaml]
----
# ubuntuをベースイメージとして使用する
FROM ubuntu:latest

# パッケージの更新、必要なパッケージのインストール
RUN apt update && apt install -y --no-install-recommends mysql-server \
 && rm -rf /var/lib/apt/lists/*

# 必要なポート（mysqlの3306番）を開く
EXPOSE 3306

# コンテナ起動時にMySQLをフォアグラウンドで起動する
CMD ["mysqld"]
----
.. イメージをビルドする。
+
[source,yaml]
----
docker build -t docker-mysql .
----
.. Dockerイメージが作成されたことを確認する。
+
[source,yaml]
----
docker images
----
作成したdocker-mysqlという名前のイメージが表示されたらOK
.. イメージにタグ付けする。
+
[source,yaml]
----
docker tag docker-mysql [Docker ID]/docker-mysql:ver1
----
.. イメージをプッシュする。
+
[source,yaml]
----
docker push [Docker ID]/docker-mysql:ver1
----
Docker Hubのページを確認し、表示されていたらOK

== Docker compose機能を利用したコンテナの起動

====








